services:
  - type: worker
    name: whatsapp-monitor
    region: oregon
    runtime: docker
    buildCommand: ""
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_TELEGRAM_TOKEN
      - key: TELEGRAM_CHAT_ID
        value: YOUR_TELEGRAM_CHAT_ID
